name: Release artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  release-artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . -t singlestoredb-extension-cpp -f Dockerfile
    - name: Build WASM binary
      run: docker run -v $PWD:/repo -w/repo singlestoredb-extension-cpp /bin/bash -c make
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          LICENSE
          *.wasm
